name: camila
favicon: null
layout_spectrum: 0.8192872074432671
typography_spectrum: 0.6345712160691619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6759860629681498
  lightness: 0.3524182755500078
  saturation: 0.9041834957897663
  rhythmicContrast: 0.08447041851468384
purpose: []
